# Generated by Django 6.0.3 on 2026-04-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_pay_stud_idx_payments_student_5b85b3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_stud_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='pay_tx_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenthistory',
            name='pay_hist_stud_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenthistory',
            name='pay_hist_date_idx',
        ),
    ]
