# Generated by Django 6.0.5 on 2026-07-09 09:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_pay_stud_idx_and_more'),
        ('programs', '0032_revert_unpaid_enrolled_to_interview_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_message',
            field=models.TextField(blank=True, help_text='Confirmation message from the bank/service for a manually recorded payment.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.CharField(blank=True, help_text='Admin email that recorded this payment manually.', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('online', 'Online (LMS)'), ('manual', 'Manual reconciliation')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('KCB', 'KCB Bank Transfer'), ('Cash', 'Cash')], max_length=20),
        ),
        migrations.CreateModel(
            name='ManualPaymentRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('KCB', 'KCB Bank Transfer'), ('Cash', 'Cash')], max_length=20)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('provider_message', models.TextField(help_text='Compulsory proof: the confirmation message sent by the bank/service.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_request', to='payments.payment')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payment_requests', to='programs.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_payment_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='manual_paym_student_5bc4bc_idx'), models.Index(fields=['status'], name='manual_paym_status_3446f3_idx'), models.Index(fields=['-created_at'], name='manual_paym_created_95ce3c_idx')],
            },
        ),
    ]
