# Generated by Django 6.0.5 on 2026-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('program', 'Program Info'), ('faq', 'FAQ'), ('policy', 'Policy'), ('contact', 'Contact'), ('admissions', 'Admissions'), ('general', 'General')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Plain text. Indexed by the AI chatbot — write clearly and factually.')),
                ('source_url', models.CharField(blank=True, help_text='Relative URL for citation, e.g. /faq', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are excluded from the chatbot index.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base',
                'db_table': 'knowledge_base',
                'ordering': ['category', 'title'],
            },
        ),
    ]
