# Generated by Django 6.0.3 on 2026-03-18 12:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('popup', 'Popup'), ('email', 'Email'), ('application', 'Application')], default='website', max_length=50)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newsletter_subscriptions',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='newsletter__email_71b1f8_idx'), models.Index(fields=['status'], name='newsletter__status_a37546_idx'), models.Index(fields=['-subscribed_at'], name='newsletter__subscri_5ee02a_idx')],
            },
        ),
    ]
