# Generated by Django 6.0.3 on 2026-04-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactmessage_options_contactmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
