# Generated by Django 6.0.3 on 2026-03-18 12:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period', models.CharField(choices=[('all-time', 'All Time'), ('monthly', 'Monthly'), ('daily', 'Daily')], max_length=20)),
                ('month_year', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics',
                'indexes': [models.Index(fields=['metric_name'], name='analytics_metric_idx'), models.Index(fields=['period'], name='analytics_period_idx'), models.Index(fields=['month_year'], name='analytics_month_year_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=10, unique=True)),
                ('new_students', models.IntegerField(default=0)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('completed_programs', models.IntegerField(default=0)),
                ('certificates_issued', models.IntegerField(default=0)),
                ('outstanding_dues', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('program_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monthly_analytics',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='monthly_ana_month_idx')],
            },
        ),
    ]
