# Generated by Django 6.0.3 on 2026-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['metric_name'], name='analytics_metric__cbd8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['period'], name='analytics_period_bae653_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['month_year'], name='analytics_month_y_a0faee_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyanalytics',
            index=models.Index(fields=['month'], name='monthly_ana_month_855d41_idx'),
        ),
    ]
