# Generated by Django 6.0.3 on 2026-04-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analytics_metric_idx_analytics_metric__cbd8a2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analytics',
            name='analytics_metric_idx',
        ),
        migrations.RemoveIndex(
            model_name='analytics',
            name='analytics_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='analytics',
            name='analytics_month_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyanalytics',
            name='monthly_ana_month_idx',
        ),
    ]
