# Generated by Django 6.0.5 on 2026-06-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendees',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
