# Generated by Django 6.0.3 on 2026-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_two_fa_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_linked',
            field=models.BooleanField(default=False),
        ),
    ]
