# Generated by Django 6.0.5 on 2026-07-22 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_alt_phone_user_city_user_country_user_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('update_application_status', 'Updated Application Status'), ('delete_application', 'Deleted Application'), ('add_application_note', 'Added Application Note'), ('propose_interview_times', 'Proposed Interview Times'), ('schedule_interview', 'Scheduled Interview'), ('reschedule_interview', 'Rescheduled Interview'), ('complete_interview', 'Completed Interview'), ('cancel_interview', 'Cancelled Interview'), ('delete_lead_program_interest', 'Deleted Program Interest Lead'), ('delete_lead_help_me', 'Deleted Help Me Lead'), ('delete_lead_incomplete', 'Deleted Incomplete Lead'), ('invite_staff', 'Invited Staff User'), ('update_staff', 'Updated Staff User'), ('remove_staff', 'Removed Staff User'), ('create_role', 'Created Role'), ('update_role', 'Updated Role'), ('delete_role', 'Deleted Role'), ('change_password', 'Changed Password'), ('change_email', 'Changed Email Address'), ('enable_2fa', 'Enabled Two-Factor Authentication'), ('disable_2fa', 'Disabled Two-Factor Authentication'), ('logout_all_sessions', 'Signed Out All Sessions'), ('upload_document', 'Uploaded Document'), ('review_document', 'Reviewed Document'), ('deactivate_account', 'Deactivated Account'), ('export_account', 'Exported Account Data'), ('delete_account', 'Deleted Account')], max_length=60),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('id', 'National ID / Passport'), ('certificate', 'Academic Certificate'), ('transcript', 'Transcript'), ('photo', 'Passport Photo'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file_url', models.URLField(max_length=2000)),
                ('file_public_id', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
