# Generated by Django 6.0.5 on 2026-07-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_auditlog_action_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('update_application_status', 'Updated Application Status'), ('delete_application', 'Deleted Application'), ('add_application_note', 'Added Application Note'), ('propose_interview_times', 'Proposed Interview Times'), ('schedule_interview', 'Scheduled Interview'), ('reschedule_interview', 'Rescheduled Interview'), ('complete_interview', 'Completed Interview'), ('cancel_interview', 'Cancelled Interview'), ('delete_lead_program_interest', 'Deleted Program Interest Lead'), ('delete_lead_help_me', 'Deleted Help Me Lead'), ('delete_lead_incomplete', 'Deleted Incomplete Lead'), ('invite_staff', 'Invited Staff User'), ('update_staff', 'Updated Staff User'), ('remove_staff', 'Removed Staff User'), ('create_role', 'Created Role'), ('update_role', 'Updated Role'), ('delete_role', 'Deleted Role'), ('change_password', 'Changed Password'), ('change_email', 'Changed Email Address'), ('enable_2fa', 'Enabled Two-Factor Authentication'), ('disable_2fa', 'Disabled Two-Factor Authentication'), ('logout_all_sessions', 'Signed Out All Sessions'), ('deactivate_account', 'Deactivated Account'), ('export_account', 'Exported Account Data'), ('delete_account', 'Deleted Account')], max_length=60),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
