# Generated by Django 6.0.3 on 2026-04-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('fullstack', 'Full Stack Development'), ('frontend', 'Frontend Development'), ('cloud', 'Cloud Computing'), ('networking', 'Networking'), ('mobile', 'Mobile Development')], max_length=50),
        ),
    ]
