# Generated by Django 6.0.3 on 2026-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_applied_at'),
    ]

    operations = [
        migrations.RunSQL("DROP INDEX IF EXISTS application_status_e61111_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS application_applied_0de066_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS application_status_a2eca9_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS application_program_af6008_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS application_course_ca6f08_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS application_email_7bef0d_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS application_applica_b16e01_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS application_changed_c6f36b_idx"),
        
        migrations.RenameField(
            model_name='application',
            old_name='course',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='course_name',
            new_name='program_name',
        ),
        
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='application_applied_0de066_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'applied_at'], name='application_status_a2eca9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['program'], name='application_program_af6008_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='application_email_7bef0d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['application'], name='application_applica_b16e01_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationlog',
            index=models.Index(fields=['changed_at'], name='application_changed_c6f36b_idx'),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.CharField(choices=[('fullstack', 'Full Stack Development Program'), ('frontend', 'Frontend Development Program'), ('cloud', 'Cloud Computing Program'), ('networking', 'Networking Program'), ('mobile', 'Mobile Development Program')], max_length=50),
        ),
    ]
