# Generated by Django 6.0.3 on 2026-04-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_app_status_idx_application_status_e61111_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='app_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='app_applied_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='app_stat_app_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='app_course_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='app_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationlog',
            name='app_log_app_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationlog',
            name='app_log_changed_idx',
        ),
    ]
