# Generated by Django 6.0.3 on 2026-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_app_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_basic_knowledge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='knowledge_description',
            field=models.TextField(blank=True),
        ),
    ]
