# Generated by Django 6.0.3 on 2026-04-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_has_basic_knowledge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('enrolled', 'Enrolled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_times', models.JSONField(default=list)),
                ('chosen_time', models.DateTimeField(blank=True, null=True)),
                ('zoom_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slot', to='applications.application')),
            ],
            options={
                'db_table': 'interview_slots',
            },
        ),
    ]
