# Generated by Django 6.0.3 on 2026-04-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_status_interviewslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
