# Generated by Django 6.0.3 on 2026-04-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_interviewslot_admin_approved_interviewslot_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
