# Generated by Django 6.0.5 on 2026-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_draftapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='gcal_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='meet_url',
            field=models.URLField(blank=True),
        ),
    ]
