# Generated by Django 6.0.5 on 2026-05-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_add_gcal_fields_interview_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the interview slot was booked by the applicant.', null=True),
        ),
    ]
