# Generated by Django 6.0.5 on 2026-06-24 08:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_fix_interviewslot_orphaned_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAdminNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=50)),
                ('html', models.TextField()),
                ('text', models.TextField(blank=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_note_logs', to='applications.application')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_admin_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_admin_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='application_applica_f9473d_idx'), models.Index(fields=['created_by'], name='application_created_2f8e3f_idx')],
            },
        ),
    ]
