# Generated by Django 6.0.5 on 2026-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_customcalendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcalendarevent',
            name='attendees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customcalendarevent',
            name='meet_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customcalendarevent',
            name='with_meet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customcalendarevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interviewblackout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interviewblackout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
