# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_add_not_reached_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('reviewed', 'Reviewed'),
                    ('not_reached', 'Not Responding'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('interview_scheduled', 'Interview Scheduled'),
                    ('interview_completed', 'Interview Completed'),
                    ('achieved', 'Achieved'),
                    ('enrolled', 'Enrolled'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
