# Generated by Django 6.0.3 on 2026-03-18 12:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in weeks')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('current_enrolled', models.IntegerField(default=0)),
                ('instructor', models.CharField(max_length=255)),
                ('instructor_email', models.EmailField(max_length=254)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('modules', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('thumbnail', models.URLField(blank=True)),
                ('syllabus', models.URLField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('offers_certificate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='programs_status_idx'), models.Index(fields=['category'], name='programs_category_idx'), models.Index(fields=['-created_at'], name='programs_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_url', models.URLField(blank=True)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=255)),
                ('verification_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked'), ('pending', 'Pending')], default='issued', max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('completion_percentage', models.IntegerField()),
                ('instructor', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='programs.program')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['student'], name='cert_student_idx'), models.Index(fields=['program'], name='cert_program_idx'), models.Index(fields=['certificate_number'], name='cert_number_idx'), models.Index(fields=['-issued_date'], name='cert_issued_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('total_hours_spent', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('modules', models.JSONField(blank=True, default=dict)),
                ('assignments', models.JSONField(blank=True, default=list)),
                ('quizzes', models.JSONField(blank=True, default=list)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('lessons_total', models.IntegerField(default=0)),
                ('tests_passed', models.IntegerField(default=0)),
                ('certificate_earned', models.BooleanField(default=False)),
                ('certificate_earned_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_progress',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student'], name='prog_prog_student_idx'), models.Index(fields=['program'], name='prog_prog_program_idx'), models.Index(fields=['status'], name='prog_prog_status_idx'), models.Index(fields=['completion_percentage'], name='prog_prog_compl_idx')],
                'unique_together': {('student', 'program')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['student'], name='enroll_student_idx'), models.Index(fields=['program'], name='enroll_program_idx'), models.Index(fields=['status'], name='enroll_status_idx'), models.Index(fields=['enrollment_date'], name='enroll_date_idx')],
                'unique_together': {('student', 'program')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgramEnrolled',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs_enrolled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_programs_enrolled',
                'indexes': [models.Index(fields=['student'], name='stud_prog_student_idx'), models.Index(fields=['program'], name='stud_prog_program_idx'), models.Index(fields=['status'], name='stud_prog_status_idx')],
                'unique_together': {('student', 'program')},
            },
        ),
    ]
