# Generated by Django 6.0.3 on 2026-04-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student'], name='certificate_student_e19697_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['program'], name='certificate_program_1530e8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='certificate_certifi_1d3ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['-issued_date'], name='certificate_issued__234caa_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollments_student_379f04_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['program'], name='enrollments_program_6c1779_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollments_status_dfab18_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_date'], name='enrollments_enrollm_4c2d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status'], name='programs_status_1f33ec_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['category'], name='programs_categor_6d4a27_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['-created_at'], name='programs_created_ff3558_idx'),
        ),
        migrations.AddIndex(
            model_name='programprogress',
            index=models.Index(fields=['student'], name='program_pro_student_cb401e_idx'),
        ),
        migrations.AddIndex(
            model_name='programprogress',
            index=models.Index(fields=['program'], name='program_pro_program_19577b_idx'),
        ),
        migrations.AddIndex(
            model_name='programprogress',
            index=models.Index(fields=['status'], name='program_pro_status_d51a95_idx'),
        ),
        migrations.AddIndex(
            model_name='programprogress',
            index=models.Index(fields=['completion_percentage'], name='program_pro_complet_7356cc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogramenrolled',
            index=models.Index(fields=['student'], name='student_pro_student_5a5e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogramenrolled',
            index=models.Index(fields=['program'], name='student_pro_program_97643f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogramenrolled',
            index=models.Index(fields=['status'], name='student_pro_status_b47f08_idx'),
        ),
    ]
