# Generated by Django 6.0.3 on 2026-04-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_cert_student_idx_certificate_student_e19697_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='certificate',
            name='cert_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='cert_program_idx',
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='cert_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='cert_issued_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enroll_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enroll_program_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enroll_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enroll_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='program',
            name='programs_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='program',
            name='programs_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='program',
            name='programs_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='programprogress',
            name='prog_prog_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='programprogress',
            name='prog_prog_program_idx',
        ),
        migrations.RemoveIndex(
            model_name='programprogress',
            name='prog_prog_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='programprogress',
            name='prog_prog_compl_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprogramenrolled',
            name='stud_prog_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprogramenrolled',
            name='stud_prog_program_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentprogramenrolled',
            name='stud_prog_status_idx',
        ),
    ]
