# Generated by Django 6.0.3 on 2026-05-02 03:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_certificate_cert_student_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_slug', models.CharField(blank=True, max_length=255)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'program_interests',
                'indexes': [models.Index(fields=['program_slug'], name='program_int_program_d08885_idx'), models.Index(fields=['email'], name='program_int_email_09fb1a_idx'), models.Index(fields=['-created_at'], name='program_int_created_92bbb9_idx')],
            },
        ),
    ]
