# Generated by Django 6.0.5 on 2026-05-30 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_programinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('max_seats', models.IntegerField(blank=True, null=True)),
                ('seats_remaining', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='site', max_length=10)),
                ('cms_id', models.CharField(blank=True, help_text='External CMS entry ID', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='programs.program')),
            ],
            options={
                'db_table': 'program_intakes',
                'ordering': ['start_date'],
                'unique_together': {('program', 'start_date')},
            },
        ),
    ]
