# Generated by Django 6.0.5 on 2026-05-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_cms_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='curriculum',
            field=models.JSONField(blank=True, default=list, help_text='[{"phase": "Month 1", "title": "...", "weeks": "4 weeks", "topics": ["..."], "project": "..."}]'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Duration in months (display only; duration stores weeks).', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "..."}]'),
        ),
        migrations.AlterField(
            model_name='program',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='[{"icon": "code", "title": "...", "desc": "..."}]'),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon',
            field=models.URLField(blank=True, help_text='Small program icon (thumbnail is the hero image).'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.URLField(blank=True, help_text='Hero/banner image URL.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Struck-through comparison price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='outcomes',
            field=models.JSONField(blank=True, default=list, help_text='["Outcome 1", "Outcome 2"]'),
        ),
        migrations.AlterField(
            model_name='program',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "React", "icon": "/icons/react.png"}]'),
        ),
    ]
