# Generated by Django 6.0.5 on 2026-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_program_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='sanity_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='programintake',
            name='sanity_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
