# Generated by Django 6.0.5 on 2026-06-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_add_sanity_id_to_program_and_intake'),
    ]

    operations = [
        # Column already exists in DB — skip DB op, register in state only
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='program',
                    name='is_featured',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in weeks', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='instructor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='instructor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
