# Generated by Django 6.0.5 on 2026-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_legacy_columns_drop_not_null'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='program',
            name='programs_categor_6d4a27_idx',
        ),
        migrations.AlterField(
            model_name='program',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
