# Generated by Django 6.0.5 on 2026-06-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_enrollment_student_nullable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='helpmelead',
            new_name='help_me_lea_email_9d85ec_idx',
            old_name='help_me_leads_email_idx',
        ),
        migrations.RenameIndex(
            model_name='helpmelead',
            new_name='help_me_lea_created_e72150_idx',
            old_name='help_me_leads_created_idx',
        ),
        migrations.RenameIndex(
            model_name='incompleteapplication',
            new_name='incomplete__email_9b25e5_idx',
            old_name='incomplete_app_email_idx',
        ),
        migrations.RenameIndex(
            model_name='incompleteapplication',
            new_name='incomplete__updated_d877af_idx',
            old_name='incomplete_app_updated_idx',
        ),
    ]
