# Generated by Django 6.0.5 on 2026-06-24 08:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_programintake_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAdminNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_type', models.CharField(choices=[('program_interest', 'Program Interest'), ('help_me', 'Help Me Lead'), ('incomplete_application', 'Incomplete Application')], max_length=40)),
                ('lead_id', models.UUIDField()),
                ('stage', models.CharField(max_length=80)),
                ('html', models.TextField()),
                ('text', models.TextField(blank=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_admin_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_admin_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead_type', 'lead_id', '-created_at'], name='lead_admin__lead_ty_6ebf5f_idx'), models.Index(fields=['created_by'], name='lead_admin__created_fe162d_idx')],
            },
        ),
    ]
