# Generated by Django 6.0.5 on 2026-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0032_revert_unpaid_enrolled_to_interview_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Resolved absolute waiver in KES, computed on save from type + value.', max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_granted_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount', 'Fixed amount')], max_length=12),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Raw waiver value: a percent (e.g. 10) or a KES amount (e.g. 5000).', max_digits=10, null=True),
        ),
    ]
